### List all text messages
GET http://localhost:3000/example

### Create a new text message using String
POST http://localhost:3000/example
Content-Type: application/json

{
  "text": "New Hello World"
}

### Create a new text message using number
POST http://localhost:3000/example
Content-Type: application/json

{
  "text": 1234
}

### Get a particular text message by id. Change the id to the one you want to get.
GET http://localhost:3000/example/583

### Get a particular text message by id that doesn't exist.
GET http://localhost:3000/example/5831231231232134234234


