### Create a report and assing it to a user.
POST http://localhost:3000/reports
content-type: application/json

{
    "make": "Toyota",
    "model": "Camry",
    "year": 2012,
    "mileage": 100000,
    "lng": 0,
    "lat": 0,
    "price": 50000
}

### Approve the existing report
PATCH http://localhost:3000/reports/109
content-type: application/json

{
    "approved": true
}

### Get an estimate for and existing vehicle
GET http://localhost:3000/reports?make=Toyota&model=Camry&year=2012&lng=0&lat=0&mileage=100000