### Create a new user
POST http://localhost:3000/auth/signup
content-type: application/json

{
    "email": "testingemailTest222515@testingdomain.com",
    "password": "TestingPassword123!@#"
}

### Sign in a user
POST http://localhost:3000/auth/signin
content-type: application/json

{
    "email": "testingemailTest222515@testingdomain.com",
    "password": "TestingPassword123!@#"
}

### Get the current signed in user
GET http://localhost:3000/auth/whoami

### Sign out a user
POST http://localhost:3000/auth/signout

### Find a particular user with a given ID.
GET http://localhost:3000/auth/14

### Find all users with a given email.
GET http://localhost:3000/auth?email=testingemailTest222512@testingdomain.com

### Delete a user with a given ID.
DELETE http://localhost:3000/auth/22123432

### Update a user with a given ID.
PATCH http://localhost:3000/auth/14
content-type: application/json

{
    "email": "testingemailTest2@testingdomain.com"
}